# Generated by Django 2.1 on 2021-04-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('discount', models.FloatField(max_length=5)),
            ],
        ),
    ]
